name: Lint (Auto-fix)
on: 
  pull_request:
    branches: [main]

permissions: 
  contents: write
  pull-requests: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - uses: actions/setup-node@v4
        with: 
          node-version: 22
          cache: 'npm'
          
      - run: npm ci
      
      - uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: true
          eslint_args: "--max-warnings 0"
          auto_fix: true
